/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Datos;
import controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class VistaMenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuAdmin
     */
    public VistaMenuUsuario() {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo_biblioteca.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonVerLibros = new javax.swing.JButton();
        botonVerRevistas = new javax.swing.JButton();
        botonVerArticulos = new javax.swing.JButton();
        botonDevolver = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(231, 255, 232));

        botonVerLibros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerLibros.setText("Ver Libros");
        botonVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerLibrosActionPerformed(evt);
            }
        });

        botonVerRevistas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerRevistas.setText("Ver Revistas");
        botonVerRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerRevistasActionPerformed(evt);
            }
        });

        botonVerArticulos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerArticulos.setText("Ver Articulos");
        botonVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArticulosActionPerformed(evt);
            }
        });

        botonDevolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonDevolver.setText("Devolver Documento Reservado");
        botonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGuardar.setText("Guardar Cambios");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENÚ USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(botonGuardar)
                            .addGap(132, 132, 132)
                            .addComponent(botonCerrarSesion))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(botonVerLibros)
                            .addGap(36, 36, 36)
                            .addComponent(botonVerArticulos)
                            .addGap(34, 34, 34)
                            .addComponent(botonVerRevistas))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(136, 136, 136)))
                    .addComponent(botonDevolver))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerLibros)
                    .addComponent(botonVerRevistas)
                    .addComponent(botonVerArticulos))
                .addGap(34, 34, 34)
                .addComponent(botonDevolver)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCerrarSesion))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerLibrosActionPerformed
        try{
           Controlador.abrirVistaLibrosUsuario(); 
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_botonVerLibrosActionPerformed

    private void botonVerRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerRevistasActionPerformed
        try{
           Controlador.abrirVistaRevistasUsuario(); 
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_botonVerRevistasActionPerformed

    private void botonVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArticulosActionPerformed
        try{
           Controlador.abrirVistaArticulosUsuario();
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonVerArticulosActionPerformed

    private void botonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverActionPerformed
        Controlador.devolverDoc();
    }//GEN-LAST:event_botonDevolverActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Controlador.guardarDocs();
        JOptionPane.showMessageDialog(null, "Cambios guardados");
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        Controlador.cerrarSesion(this);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonDevolver;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVerArticulos;
    private javax.swing.JButton botonVerLibros;
    private javax.swing.JButton botonVerRevistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
