/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Datos;
import controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class VistaMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuAdmin
     */
    public VistaMenuAdmin() {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo_biblioteca.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonVerLibros = new javax.swing.JButton();
        botonVerRevistas = new javax.swing.JButton();
        botonVerArticulos = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonNuevaRevista = new javax.swing.JButton();
        botonNuevoArticulo = new javax.swing.JButton();
        botonNuevoLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(231, 255, 232));

        botonVerLibros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerLibros.setText("Ver Libros");
        botonVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerLibrosActionPerformed(evt);
            }
        });

        botonVerRevistas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerRevistas.setText("Ver Revistas");
        botonVerRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerRevistasActionPerformed(evt);
            }
        });

        botonVerArticulos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonVerArticulos.setText("Ver Articulos");
        botonVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArticulosActionPerformed(evt);
            }
        });

        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGuardar.setText("Guardar Cambios");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonNuevaRevista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonNuevaRevista.setText("Añadir Revista");
        botonNuevaRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaRevistaActionPerformed(evt);
            }
        });

        botonNuevoArticulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonNuevoArticulo.setText("Añadir Artículo");
        botonNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoArticuloActionPerformed(evt);
            }
        });

        botonNuevoLibro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonNuevoLibro.setText("Añadir Libro");
        botonNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoLibroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENÚ ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevaRevista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNuevoLibro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNuevoArticulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCerrarSesion)
                    .addComponent(botonVerArticulos)
                    .addComponent(botonVerLibros)
                    .addComponent(botonVerRevistas))
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerLibros)
                    .addComponent(botonNuevoLibro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerArticulos)
                    .addComponent(botonNuevoArticulo))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaRevista)
                    .addComponent(botonVerRevistas))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCerrarSesion))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerLibrosActionPerformed
        try{
           Controlador.abrirVistaLibrosAdmin(); 
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_botonVerLibrosActionPerformed

    private void botonVerRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerRevistasActionPerformed
        try{
           Controlador.abrirVistaRevistasAdmin(); 
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_botonVerRevistasActionPerformed

    private void botonVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArticulosActionPerformed
        try{
           Controlador.abrirVistaArticulosAdmin();
        }catch(IndexOutOfBoundsException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonVerArticulosActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        Controlador.cerrarSesion(this);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoLibroActionPerformed
        Controlador.abrirVistaCrearLibro();
    }//GEN-LAST:event_botonNuevoLibroActionPerformed

    private void botonNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoArticuloActionPerformed
        Controlador.abrirVistaCrearArticulo();
    }//GEN-LAST:event_botonNuevoArticuloActionPerformed

    private void botonNuevaRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaRevistaActionPerformed
        Controlador.abrirVistaCrearRevista();
    }//GEN-LAST:event_botonNuevaRevistaActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Controlador.guardarDocs();
        JOptionPane.showMessageDialog(null, "Cambios guardados");
    }//GEN-LAST:event_botonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevaRevista;
    private javax.swing.JButton botonNuevoArticulo;
    private javax.swing.JButton botonNuevoLibro;
    private javax.swing.JButton botonVerArticulos;
    private javax.swing.JButton botonVerLibros;
    private javax.swing.JButton botonVerRevistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
